### ISSUE TITLE
native-platform fails to run on FreeBSD 10 without gcc

### ISSUE THREAD

**Issue by rpmoore** [adammurdoch/native-platform#10] opened 2015-04-28 21:25 UTC
The standard distribution for FreeBSD 10 does not include gcc, but includes clang instead.  This causes the native-platform to fail to run.  The native-platform should be updated to build with clang on FreeBSD so as to not require users to install gcc in addition to clang.

**Comment by asomers** [comment] 2016-06-03 14:50
Strictly speaking, the problem isn't the compiler; it's the standard library.  FreeBSD 10 (and soon, 11) include libc++, but not libstdc++

**Comment by adammurdoch** [comment] 2016-11-13 05:57
This is fixed in 0.12. Thanks for reporting.

**Closed by adammurdoch** 2016-11-13 05:57 UTC
